[project]
name = "protocol"
authors = []
description = ""
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"

# Base DAO

[contracts.base-dao]
path = "contracts/base-dao.clar"
depends_on = ["proposal-trait", "extension-trait"]

# Extensions

[contracts.ccd001-direct-execute]
path = "contracts/extensions/ccd001-direct-execute.clar"
depends_on = ["base-dao"]

[contracts.ccd002-treasury]
path = "contracts/extensions/ccd002-treasury.clar"
depends_on = ["base-dao", "sip009-nft-trait", "sip010-ft-trait"]

# Proposals

[contracts.ccip012-bootstrap]
path = "contracts/proposals/ccip012-bootstrap.clar"
depends_on = ["base-dao", "ccd001-direct-execute"]

## Test Specific Proposals

[contracts.ccip-test-proposal-001]
path = "tests/proposals/ccip-test-proposal-001.clar"
depends_on = ["proposal-trait", "ccd001-direct-execute"]

# DAO Traits

[contracts.extension-trait]
path = "contracts/traits/extension-trait.clar"
depends_on = []

[contracts.proposal-trait]
path = "contracts/traits/proposal-trait.clar"
depends_on = []

# Stacks Traits

[contracts.sip009-nft-trait]
path = "contracts/traits/sip009-nft-trait.clar"
depends_on =  []

[contracts.sip010-ft-trait]
path = "contracts/traits/sip010-ft-trait.clar"
depends_on =  []

# REPL settings

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
